version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
      - type: bind
        source: ./elastic-certificates.p12
        target: /usr/share/elasticsearch/config/elastic-certificates.p12
        read_only: true

  logstash:
    image: logstash:7.9.3
    container_name: logstash
    ports:
      - "4560:4560/tcp"
      - "4560:4560/udp"
      - "9600:9600"
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.9.3
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    restart: on-failure
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
